### ISSUE TITLE
Choose install MixEdit

### ISSUE THREAD

**Issue by Nisgrak** [justcla/SublimeVS#3]
We can't buy a license for MixEdit anymore, so make optional MixEdit or remove them for enviroments where piracy isn't a option please!

**Comment by LiamKarlMitchell** [comment]
A shame, it's got such nice features that should be in any modern editor by default...
The Demo has a nag prompt that steals focus.

The site/license says this.
```
Businesses must purchase at least as many licenses as the number of people using MixEdit. 
```

```
The sale of MixEdit has been suspended until further notice.
We apologise for the inconvenience and we encourage you to keep using MixEdit on the base license for personal non commercial use.
```
So the developer tells us to use it as-is even for commercial purposes, does that legitimately negate their previous terms for a license being required?

**Comment by justcla** [comment]
The features implemented in MixEdit are really important to the Sublime experience. I agree it's annoying to see the licence pop-up, but there aren't many good alternatives.
I've attempted to reach out to the author on several occasions, but I've never had a response.
As noted above, there is a notice on the website that says that they've suspended sales, but that we're encouraged to keep using it for personal use. I believe that means people are free to use the software without paying for it - for the time being.

**Comment by jakubsuchybio** [comment]
If he seised sales, then I guess his Licence policies doesn't apply too. So if you guys need a licence, contact me and I will borrow you mine. I bought MixEdit a while ago, but had to uninstall it because it lags VS so much... I am in the process or duplicating this extension myself, but I am still too far away.

**Comment by justcla** [comment]
Thanks @jakubsuchybio 
Can you post the licence key here?

**Comment by justcla** [comment]
@jakubsuchybio , if you're looking to re-write something like Mix-Edit, let's talk. I'm doing similar work in extensions and in the core product, so perhaps we can share our work rather than duplicating efforts.

**Comment by jakubsuchybio** [comment]
@justcla Well... I didn't want to do this, but at the other hand... Why not :)
MixEdit licence
User Name: "jakubsuchybio"
Product Key: "M12O4G4O4O1E591G112B30 0D2I281B1P3G5T4Y4A24 4M13730T6U792B2W103L 363B650K5W1D255G2B30 0M3537493J3G3R6I7143 2F2S3O1R310L6G5N3T3M 1X1N0P3C4I2127270G44 2G1X6V0Q3K2M473C5X19 6T5T490B6Y0E3U6C4Q34 4D1J3E0P161L664G3D6A 425C5P1A0D0M2T791G57 6X3H25641R14062U205Q 3Y0O14733E66141U"

Hit me at biosek@pm.me so we can exchange some faster communications.

**Comment by justcla** [comment]
I have removed MixEdit from SublimeVS and replaced it with SelectNextOccurrence.

**Comment by VinodParmar** [comment]
Thanks its working for me.
