### ISSUE TITLE
How to remove this?

### ISSUE THREAD

**Issue by sk29110** [justcla/SublimeVS#4]
I installed this but now want to remove this. how to remove this extension? It doesn't show up in the list of extensions installed.

**Comment by justcla** [comment]
If it's not showing up in the list of extensions installed, what make you think it's installed?

**Comment by sk29110** [comment]
I have going through the installation minimap started showing up. Unfortunately it slows down my visual studio so I want to get rid of it now.

**Comment by justcla** [comment]
MiniMap is a part of Visual Studio. Visual Studio call it "Map Mode".

To turn it off, right click the scroll bar and choose "Scroll Bar Options..."
Then choose the "Use bar mode for vertical scroll bar".

**Comment by sk29110** [comment]
ok I never knew.

**Comment by justcla** [comment]
... You're welcome, I guess.
