### ISSUE TITLE
Support for other version of Visual Studio 201x

### ISSUE THREAD

**Issue by Alexisvt** [justcla/SublimeVS#7]
Hi, first of all I want to say thank you for this project! I'v been using this extension and to be honest, after install it, I feel I really enjoy again to work with Visual Studio! But now I'm working in another version of Visua Studio, Im working on VS2015 and now Im sad again because I discovered that this extension is not available on that version, I want to ask if there is a way to extend the support if it to other versions of VS, thanks!

**Comment by justcla** [comment]
Hi Alexisvt. Sorry for the late reply. In theory, yes, I believe this extension could be adjusted to run in VS2015.

Alternatively, You can just install the bundled extensions straight from the Marketplace.
Then you can apply the shortcuts.
