### ISSUE TITLE
Support for Visual Studio 2019

### ISSUE THREAD

**Issue by julihermes** [justcla/SublimeVS#8]
The most extensions used in this bundle is already support VS2019, any plans to support too?

**Comment by DanBrink91** [comment]
I would love this as well

**Comment by farrrb** [comment]
Yes, I totally agree. Please give us an update :) (And thanks in advance!)

**Comment by nelsondev** [comment]
Just giving support so I can use this extension in vs 2019

**Comment by justcla** [comment]
Received. I haven't forgotten.

**Comment by ghost** [comment]
Would like to see update for VS2019👍👍👍

**Comment by Alzy** [comment]
Will we ever see this for VS2019?

**Comment by justcla** [comment]
I dunno. There's a lot of extensions to upgrade. It's not just one. It
involves a collection of extensions that all need to be upgraded.

**Comment by justcla** [comment]
OK - All extensions have been upgraded to VS2019 except EasyMotion. I've upgraded EasyMotion locally and sent the PR to @jaredpar.
I'll see if I can rebundle all the extensions and release a version that runs on VS2019.

**Comment by justcla** [comment]
I have upgraded the extension for VS2019 and handled the Async issues.
The new extension (v1.2.1) is now available on the Marketplace.
Enjoy!

**Comment by Alzy** [comment]
Amazing! Thank you

**Comment by julihermes** [comment]
Thank you!
